---
- name: pull jupyterhub service images
  command: docker pull {{ item }}
  with_items:
  - jupyter/systemuser
  sudo: yes
  tags:
    - docker-rebuild

- name: create the systemuser directory
  file: path=/srv/systemuser state=directory
  sudo: yes
  tags:
    - docker-rebuild

- name: copy the Dockerfile to the systemuser directory
  copy:
    src: Dockerfile_systemuser
    dest: /srv/systemuser/Dockerfile
  sudo: yes
  tags:
    - docker-rebuild

- name: build compmodels/systemuser image
  docker_image:
    path: /srv/systemuser
    name: compmodels/systemuser
    state: build
  sudo: yes
  tags:
    - docker-rebuild

