---
- hosts: jupyterhub_host
  vars_files:
    - 'secrets.vault.yml'
    - 'users.vault.yml'
    - 'vars.yml'

  vars_prompt:
    assignment: "Which assignment?"

  tasks:
    - name: create /srv/assignments
      file: path=/srv/assignments state=directory
      sudo: yes

    - name: collect submissions
      collect_submissions:
        src: '.nbgrader/submissions/{{ assignment }}.tar.gz'
        dest: '/srv/assignments/submissions.tar.gz'
        users: "{{ students }}"
        overwrite: yes
      sudo: yes

    - name: download submissions
      fetch:
        src: '/srv/assignments/submissions.tar.gz'
        dest: '{{ assignment_path }}/{{ assignment }}/submissions.tar.gz'
        flat: yes
        fail_on_missing: yes
      sudo: yes
