---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ['secrets.yml', 'secrets.vault.yml']
    - ['vars.local.yml', 'vars.yml']

  tasks:
    - name: create assignment
      make_assignment:
        src: '{{ assignment_path }}/{{ assignment }}/release'
        name: '{{ assignment }}'
        dest: '/tmp/assignment.tar.gz'
        overwrite: yes

  vars_prompt:
    assignment: "Which assignment?"

- hosts: jupyterhub_host
  vars_files:
    - ['secrets.yml', 'secrets.vault.yml']
    - ['vars.local.yml', 'vars.yml']

  tasks:
    - name: create /srv/assignments
      file: path=/srv/assignments state=directory
      sudo: yes

    - name: upload assignment
      copy:
        src: '/tmp/assignment.tar.gz'
        dest: '/srv/assignments/assignment.tar.gz'

    - name: create /srv/skeldir
      file: path=/srv/skeldir state=directory
      sudo: yes

    - name: extract assignment to skeleton directory
      unarchive:
        copy: no
        src: /srv/assignments/assignment.tar.gz
        dest: /srv/skeldir
      sudo: yes

    - name: extract assignment to user directories
      release_assignment:
        src: '/srv/assignments/assignment.tar.gz'
        users: "{{ students | union(instructors) }}"
