---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - 'secrets.vault.yml'
    - ['vars.local.yml', 'vars.yml']

  tasks:
    - name: create feedback
      make_feedback:
        src: '{{ assignment_path }}/{{ assignment }}/feedback'
        name: '{{ assignment }}'
        dest: '/tmp/feedback.tar.gz'
        overwrite: yes

  vars_prompt:
    assignment: "Which assignment?"

- hosts: jupyterhub_host
  vars_files:
    - 'secrets.vault.yml'
    - 'users.vault.yml'
    - ['vars.local.yml', 'vars.yml']

  tasks:
    - name: remove existing feedback
      file: path=/srv/assignments/feedback state=absent
      sudo: yes

    - name: create /srv/assignments/feedback
      file: path=/srv/assignments/feedback state=directory
      sudo: yes

    - name: upload and extract feedback
      unarchive:
        src: '/tmp/feedback.tar.gz'
        dest: '/srv/assignments/feedback'
      sudo: yes

    - name: extract feedback to user directories
      return_feedback:
        src: '/srv/assignments/feedback'
        overwrite: no
      sudo: yes
