---
- hosts: jupyterhub
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - ['vars.local.yml', 'vars.yml']
  roles:
  - common
  - jupyterhub

- hosts: proxy
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - ['vars.local.yml', 'vars.yml']
  roles:
  - common
  - proxy
