---
- hosts:
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - ['vars.local.yml', 'vars.yml']
  roles:
  - common
  - docker

- hosts:
  - jupyterhub_host
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - ['vars.local.yml', 'vars.yml']
  roles:
  - nfs-server

- hosts: jupyterhub_nodes
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - ['vars.local.yml', 'vars.yml']
  roles:
  - nfs
  - jupyterhub_node

- hosts: jupyterhub_host
  vars_files:
  - ['secrets.yml', 'secrets.vault.yml']
  - ['vars.local.yml', 'vars.yml']
  roles:
  - jupyterhub_host
