---
- name: nginx
  apt: name=nginx state=present
  sudo: yes

- name: SSL credentials
  template: src={{ item.from }} dest={{ item.to }} mode=0644
  with_items:
  - from: tmpnb.org.key.j2
    to: "{{ ssl_key_path }}"
  - from: tmpnb.org.crt.j2
    to: "{{ ssl_cert_path }}"
  sudo: yes
  notify:
  - restart nginx

- name: nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default mode=0644
  sudo: yes
  notify:
  - restart nginx
