---
- name: pull jupyterhub service images
  command: docker pull {{ item }}
  with_items:
  - jhamrick/systemuser
  - jhamrick/jupyterhub
  sudo: yes
  tags:
    - docker-rebuild

- name: create the jupyterhub directory
  file: path=/srv/jupyterhub state=directory
  sudo: yes
  tags:
    - docker-rebuild

- name: copy the Dockerfile to the jupyterhub directory
  copy:
    src: Dockerfile
    dest: /srv/jupyterhub/Dockerfile
  sudo: yes
  tags:
    - docker-rebuild

- name: create the userlist
  template: src=userlist.j2 dest=/srv/jupyterhub/userlist
  sudo: yes
  tags:
    - docker-rebuild

- name: build jhamrick/compmodels-jupyterhub:deploy image
  docker_image:
    path: /srv/jupyterhub
    name: jhamrick/compmodels-jupyterhub
    tag: deploy
    state: build
  sudo: yes
  tags:
    - docker-rebuild
