---
- name: pull jupyterhub service images
  command: docker pull {{ item }}
  with_items:
  - jupyter/systemuser
  - jupyter/jupyterhub
  sudo: yes
  tags:
    - docker-rebuild

- name: create the jupyterhub directory
  file: path=/srv/jupyterhub state=directory
  sudo: yes
  tags:
    - docker-rebuild

- name: copy the Dockerfile to the jupyterhub directory
  copy:
    src: Dockerfile_jupyterhub
    dest: /srv/jupyterhub/Dockerfile
  sudo: yes
  tags:
    - docker-rebuild

- name: copy jupyterhub_config.py to the jupyterhub directory
  copy:
    src: jupyterhub_config.py
    dest: /srv/jupyterhub/jupyterhub_config.py
  sudo: yes
  tags:
    - docker-rebuild

- name: create the userlist
  template: src=userlist.j2 dest=/srv/jupyterhub/userlist
  sudo: yes
  tags:
    - docker-rebuild

- name: build compmodels/jupyterhub image
  docker_image:
    path: /srv/jupyterhub
    name: compmodels/jupyterhub
    state: build
  sudo: yes
  tags:
    - docker-rebuild

- name: create the systemuser directory
  file: path=/srv/systemuser state=directory
  sudo: yes
  tags:
    - docker-rebuild

- name: copy the Dockerfile to the systemuser directory
  copy:
    src: Dockerfile_systemuser
    dest: /srv/systemuser/Dockerfile
  sudo: yes
  tags:
    - docker-rebuild

- name: build compmodels/systemuser image
  docker_image:
    path: /srv/systemuser
    name: compmodels/systemuser
    state: build
  sudo: yes
  tags:
    - docker-rebuild
