---
- name: tweak grub settings
  lineinfile:
    dest: /etc/default/grub
    regexp: GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
  register: grubbed
  sudo: yes

- name: apply changed grub settings
  command: update-grub
  sudo: yes
  when: grubbed | changed

- include: docker.yml

- name: pull tmpnb service images
  command: docker pull {{ item }}
  with_items:
  - jhamrick/oauthenticator
  - jhamrick/singleuser
  sudo: yes

- name: reboot
  command: shutdown -r now "Ansible updated grub"
  async: 0
  poll: 0
  sudo: yes
  ignore_errors: true
  when: grubbed | changed

- name: wait for server to relaunch
  local_action: wait_for host={{ inventory_hostname }} state=started
  when: grubbed | changed

- name: iptables configuration
  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000
  sudo: yes

- name: jupyterhub
  docker:
    state: running
    image: jhamrick/oauthenticator
    detach: true
    net: host
    name: tmpnb
    env:
      FAKE: "test"
    # TODO: Bring these in from the vault
    #  GITHUB_CLIENT_ID: "{{ github_client_id }}"
    #  GITHUB_CLIENT_SECRET: "{{ github_client_secret }}"
    #  OAUTH_CALLBACK_URL: "{{ oauth_callback_url }}"
    volumes: /var/run/docker.sock:/docker.sock
