---
- name: tweak grub settings
  lineinfile:
    dest: /etc/default/grub
    regexp: GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
  register: grubbed
  sudo: yes

- name: apply changed grub settings
  command: update-grub
  sudo: yes
  when: grubbed | changed

- include: docker.yml
- include: docker-build.yml

- name: reboot
  command: shutdown -r now "Ansible updated grub"
  async: 0
  poll: 0
  sudo: yes
  ignore_errors: true
  when: grubbed | changed

- name: wait for server to relaunch
  local_action: wait_for host={{ inventory_hostname }} state=started
  when: grubbed | changed

- name: iptables configuration
  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000
  sudo: yes

- include: accounts.yml

- name: stop running docker containers
  shell: docker stop $(docker ps -a -q) || true
  tags:
    - docker-rebuild

- name: remove docker containers
  shell: docker rm $(docker ps -a -q) || true
  tags:
    - docker-rebuild

- name: create jupyterhub.sqlite
  file: path=/srv/jupyterhub/jupyterhub.sqlite state=touch mode=0600

- name: launch jupyterhub
  docker:
    state: running
    image: jhamrick/compmodels-jupyterhub:deploy
    detach: true
    net: host
    name: jupyterhub
    env:
      GITHUB_CLIENT_ID: "{{ github_client_id }}"
      GITHUB_CLIENT_SECRET: "{{ github_client_secret }}"
      OAUTH_CALLBACK_URL: "{{ oauth_callback_url }}"
      JPY_COOKIE_SECRET: "{{ cookie_secret }}"
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
    volumes:
        - /var/run/docker.sock:/docker.sock
        - /var/run/restuser.sock:/restuser.sock
        - /srv/jupyterhub/jupyterhub.sqlite:/srv/oauthenticator/jupyterhub.sqlite
  tags:
    - docker-rebuild
