---
- name: stop and remove stats container
  docker:
    state: absent
    image: compmodels/stats
    name: stats
  sudo: yes
  tags:
    - stats
    - docker-rebuild

- name: create the /srv/stats directory
  file: path=/srv/stats state=directory
  sudo: yes
  tags:
    - stats
    - docker-rebuild

- name: create the /srv/stats/db directory
  file: path=/srv/stats/db state=directory
  sudo: yes
  tags:
    - stats
    - docker-rebuild

- name: copy the Dockerfile to /srv/stats
  copy: src=Dockerfile_stats dest=/srv/stats/Dockerfile
  sudo: yes
  tags:
    - stats
    - docker-rebuild

- name: build compmodels/stats image
  docker_image:
    path: /srv/stats
    name: compmodels/stats
    state: build
  sudo: yes
  tags:
    - stats
    - docker-rebuild

- name: launch stats
  docker:
    state: running
    image: compmodels/stats
    detach: true
    name: stats
    net: host
    env:
      JPY_API_TOKEN: "{{ jpy_api_token.stdout }}"
    volumes:
        - /srv/stats/db:/srv/stats/db
  sudo: yes
  tags:
    - stats
    - docker-rebuild
