---
- name: install vim for ops sanity
  apt: update_cache=yes cache_valid_time=600 name=vim state=latest
  sudo: yes

- name: YOLO system upgrade
  apt: upgrade=safe
  sudo: yes

- include: ssh.yml
- include: python.yml
