---
- name: install mdadm
  apt: update_cache=yes cache_valid_time=600 name=mdadm state=latest
  sudo: yes
  tags:
    - nfs

- name: run the lsi-cards script
  script: lsi-cards {{ ansible_fqdn }} /var/lib/docker creates=/etc/{{ ansible_fqdn }}.raid-setup
  sudo: yes
  tags:
    - nfs

- name: install nfs server
  apt: name=nfs-kernel-server,nfs-common state=latest
  sudo: yes
  tags:
    -nfs

- name: ensure nfs service is running
  action: service name=nfs-kernel-server state=started
  sudo: yes
  tags:
    - nfs

- name: create symlink from /var/lib/docker/export to /students
  file: src=/var/lib/docker/export dest=/students state=link
  sudo: yes
  tags:
    - nfs
